# Generated by Django 5.0 on 2024-01-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_order_order_count_alter_bookreview_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_count',
        ),
    ]
