# Generated by Django 5.0 on 2024-01-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_remove_order_order_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_books/')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='bookstore.book')),
            ],
        ),
    ]
