# Generated by Django 5.0 on 2024-01-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Cart',
            new_name='cart',
        ),
    ]
