# Generated by Django 5.0 on 2024-01-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='books',
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.wishlist')),
            ],
        ),
    ]
