# Generated by Django 5.0 on 2024-01-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_wishlistitem_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating gor the book', max_digits=3),
        ),
    ]
