# Generated by Django 5.0 on 2024-01-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_alter_bookreview_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'books')},
        ),
    ]
