# Generated by Django 5.0 on 2024-01-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
